language: objective-c
os: osx

env:
  global:
    # $api_key
    - secure: vjVOdxnuHnkDiPXoddLycTQ2WwbYudHU53xbaz86Su0J+xTSNDmxmd2GFn45EMn5BixwVzTnLWhDg7EvNvQhHWDAuHUaK7X/KXoR41s3PzlucWtxczxxt3eIRtk7U4y22tSwr/r1cl6Q2QM5IK8ICZshhSyiHHEz/EAaodcJkUE=
    - XCODE_WORKSPACE=FacebookSDK.xcworkspace
    - GITHUB_ACCESS_TOKEN=$api_key

branches:
  only:
    - master
    - 4.x-branch
    - /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

stages:
  - name: test
    if: '! tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  - name: release
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/
  - name: release cocoapods 1/3
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/
  - name: release cocoapods 2/3
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/
  - name: release cocoapods 3/3
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/
  - name: verify release
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

jobs:
  include:
    - stage: test
      name: Xcode - iOS 13
      osx_image: xcode11
      env:
        - XCODE_SDK=iphonesimulator13.0
        - XCODE_SCHEME=BuildAllKits
    - stage: test
      name: Xcode - tvOS 13
      osx_image: xcode11
      env:
        - XCODE_SDK=appletvsimulator13.0
        - XCODE_SCHEME=BuildAllKits_TV
    - stage: test
      name: Carthage
      osx_image: xcode11
    - stage: test
      name: Pod Lint
      osx_image: xcode11
      script: sh scripts/run.sh lint cocoapods
    - stage: test
      name: Pod Lint Static
      osx_image: xcode11
      script: sh scripts/run.sh lint cocoapods --use-libraries
    - stage: test
      name: Swift Lint
      osx_image: xcode11
      script: sh scripts/run.sh lint swift
    - stage: test
      name: Verify Swift Package Headers
      script: sh scripts/run.sh verify-spm-headers
    - stage: test
      name: Swift Package Integration Test
      osx_image: xcode11.2
      script: sh scripts/run.sh build spm-integration
    - stage: test
      name: Build Swift Packages
      osx_image: xcode11.2
      script: sh scripts/run.sh build spm
    - stage: release
      name: GitHub Release
      osx_image: xcode11
      script: sh scripts/run.sh release github
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_ACCESS_TOKEN
        file: build/Release/*
        file_glob: true
        name: Facebook SDK $TRAVIS_TAG
        body: Consult Changelog $TRAVIS_TAG
        on:
          all_branches: true
          tags: true
    - stage: release cocoapods 1/3
      name: Release Top Level Cocoapods
      osx_image: xcode11
      script: sh scripts/run.sh release cocoapods FBSDKCoreKit
    - stage: release cocoapods 2/3
      name: Release Dependent Cocoapods
      osx_image: xcode11
      script: sh scripts/run.sh release cocoapods FBSDKLoginKit FBSDKShareKit
    - stage: release cocoapods 3/3
      name: Release Dependent Cocoapods
      osx_image: xcode11
      script: sh scripts/run.sh release cocoapods FBSDKGamingServicesKit FBSDKTVOSKit
    - stage: verify release
      osx_image: xcode 11.3
      script: sh scripts/run.sh check-release-status

script: sh scripts/travis/script.sh

notifications: # set notification options
  email:
    on_success: change
    on_failure: always
    recipients:
      - joesusnick@fb.com
      - tianqibt@fb.com
      - kylinchang@fb.com
  # Enable webhooks later
  # webhooks:
  # on_failure: always
