language: objective-c
os: osx

env:
  global:
    - XCODE_WORKSPACE=FacebookSDK.xcworkspace
    - secure: vjVOdxnuHnkDiPXoddLycTQ2WwbYudHU53xbaz86Su0J+xTSNDmxmd2GFn45EMn5BixwVzTnLWhDg7EvNvQhHWDAuHUaK7X/KXoR41s3PzlucWtxczxxt3eIRtk7U4y22tSwr/r1cl6Q2QM5IK8ICZshhSyiHHEz/EAaodcJkUE=
    - secure: uHizSYU7rXsnRjb6NS0KrIIwII4ouefDaDW1OJkvgFaoIoL2hqqP6q3vILZaY2bGiTnU7RnDxGvbwy7dr2w8Q9Rp4djpeRkTyHP+slzAl8b0LD034uB4q/3KPtc607atyYiMNoeeOCWe4j3tnMU2EFI+/mH8gr5i/zIlG1FQwfdl+dFznriS4tb2x8tIdcUnkxSN/yJAwUCzRe/G4jOBCqMFpe8a73K3VJsdjvuCsfJprH3YJTNtjFqdUkzxiGk/Pv72gty3bjvEskfcDj8uMy1Jcq40/+he8fHO5RX+AxGNdU2u/XpUSwMddu8mEinc9GiLyogYRoKI0C+8MjBWg+sUOOPXJOSXAAOcxclyCI8kfYaUe5MePeAqCQiU8+b9WXwz8yoJFXkF2+6G73Q776SwBLfUtGDHU88gV+/TT3+4wqO/CM0rZEWzCrQ5NE2dBEaQ1sYHLIr+VC8rL/QWzhMil09QlLBuv7zOLEMvyhr/FX3fwbNCxd/7USBc/V0Cnp2HCvJwhQ3xobFlrzwzidnKCs3BhRs3FpVQgwwcvwgpIKFzoVQQZ1ZTF2ICYJH6LQkElt3xAd2iklrrqJDRjSw1Il6l3wD3nS3F7mlxnMpwk/1rkogyMY/gqw0JNLjnQGJWaG4/qoJvHD7ZjGfZZn32AzubQ2/UTcMiy0i3kr4= # COCOAPODS_TRUNK_TOKEN

stages:
  - name: test
    if: '! tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  # - name: tag
  #   if: '! tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  - name: release
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

jobs:
  include:
    - name: Xcode - iOS 12.0
      osx_image: xcode10.1
      env:
        - XCODE_SDK=iphonesimulator12.1
        - XCODE_SCHEME=BuildAllKits
    - name: Xcode - tvOS 12.0
      osx_image: xcode10.1
      env:
        - XCODE_SDK=appletvsimulator12.1
        - XCODE_SCHEME=BuildAllKits_TV
    - name: Xcode - iOS 11.4
      osx_image: xcode9.4
      env:
        - XCODE_SDK=iphonesimulator11.4
        - XCODE_SCHEME=BuildAllKits
    - name: Carthage - Xcode 10.1
      osx_image: xcode10.1
      if: tag IS blank
    # - stage: tag
    #   name: Tag Version
    #   osx_image: xcode10.1
    #   script: sh scripts/run.sh tag-push-current-version
    - stage: release
      name: GitHub
      osx_image: xcode10.1
      script: sh scripts/run.sh build carthage --archive
      deploy:
        - provider: releases
          skip_cleanup: true
          api_key:
            secure: vjVOdxnuHnkDiPXoddLycTQ2WwbYudHU53xbaz86Su0J+xTSNDmxmd2GFn45EMn5BixwVzTnLWhDg7EvNvQhHWDAuHUaK7X/KXoR41s3PzlucWtxczxxt3eIRtk7U4y22tSwr/r1cl6Q2QM5IK8ICZshhSyiHHEz/EAaodcJkUE=
          file: Carthage/Release/*
          file_glob: true
          on:
            all_branches: true
            condition:
              tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/
        - provider: script
          script: sh scripts/run.sh release cocoapods --allow-warnings
          on:
            all_branches: true
            condition:
              tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

before_install: sh scripts/travis/before_install.sh
install: sh scripts/travis/install.sh
script: sh scripts/travis/script.sh

notifications: # set notification options
  email:
    on_success: change
    on_failure: always
    recipients:
      - codytwinton@fb.com
  # Enable webhooks later
  # webhooks:
  # on_failure: always
